// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {localcal} from '../models';
import {main} from '../models';
import {calendar} from '../models';
import {config} from '../models';
import {holidays} from '../models';
import {k8s} from '../models';
import {sysmon} from '../models';
import {weather} from '../models';

export function AddLocalEvent(arg1:localcal.Event):Promise<localcal.Event>;

export function CordonK8sNode(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteK8sPod(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteLocalEvent(arg1:string):Promise<void>;

export function DrainK8sNode(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ForceKillProcess(arg1:number):Promise<void>;

export function GetCalendarEvents(arg1:Array<main.CalendarAccountInput>,arg2:number):Promise<Array<calendar.Event>>;

export function GetConfig():Promise<config.Config>;

export function GetHolidays(arg1:number):Promise<Array<holidays.Holiday>>;

export function GetHolidaysRange(arg1:number,arg2:number):Promise<Array<holidays.Holiday>>;

export function GetK8sClusterDetail(arg1:string,arg2:string):Promise<k8s.ClusterDetail>;

export function GetK8sDeployments(arg1:string,arg2:string,arg3:string):Promise<Array<k8s.DeploymentInfo>>;

export function GetK8sNodeMetrics(arg1:string,arg2:string):Promise<Array<k8s.NodeMetrics>>;

export function GetK8sPodLogs(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<string>;

export function GetK8sPods(arg1:string,arg2:string,arg3:string):Promise<Array<k8s.PodInfo>>;

export function GetK8sServices(arg1:string,arg2:string,arg3:string):Promise<Array<k8s.ServiceInfo>>;

export function GetK8sStatuses(arg1:string,arg2:Array<string>):Promise<Array<k8s.ClusterStatus>>;

export function GetLocalEvents(arg1:string,arg2:string):Promise<Array<localcal.Event>>;

export function GetSystemStats():Promise<sysmon.SystemStats>;

export function GetTopProcesses(arg1:string,arg2:number):Promise<Array<sysmon.ProcessInfo>>;

export function GetWeather(arg1:Array<string>,arg2:number):Promise<Array<weather.CityWeather>>;

export function KillProcess(arg1:number):Promise<void>;

export function ResetConfig():Promise<config.Config>;

export function RestartK8sDeployment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ScaleK8sDeployment(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function UncordonK8sNode(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateLocalEvent(arg1:localcal.Event):Promise<void>;
