// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLocalEvent(arg1) {
  return window['go']['main']['App']['AddLocalEvent'](arg1);
}

export function CordonK8sNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['CordonK8sNode'](arg1, arg2, arg3);
}

export function DeleteK8sPod(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteK8sPod'](arg1, arg2, arg3, arg4);
}

export function DeleteLocalEvent(arg1) {
  return window['go']['main']['App']['DeleteLocalEvent'](arg1);
}

export function DrainK8sNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['DrainK8sNode'](arg1, arg2, arg3);
}

export function ForceKillProcess(arg1) {
  return window['go']['main']['App']['ForceKillProcess'](arg1);
}

export function GetCalendarEvents(arg1, arg2) {
  return window['go']['main']['App']['GetCalendarEvents'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHolidays(arg1) {
  return window['go']['main']['App']['GetHolidays'](arg1);
}

export function GetHolidaysRange(arg1, arg2) {
  return window['go']['main']['App']['GetHolidaysRange'](arg1, arg2);
}

export function GetK8sClusterDetail(arg1, arg2) {
  return window['go']['main']['App']['GetK8sClusterDetail'](arg1, arg2);
}

export function GetK8sDeployments(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetK8sDeployments'](arg1, arg2, arg3);
}

export function GetK8sNodeMetrics(arg1, arg2) {
  return window['go']['main']['App']['GetK8sNodeMetrics'](arg1, arg2);
}

export function GetK8sPodLogs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetK8sPodLogs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetK8sPods(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetK8sPods'](arg1, arg2, arg3);
}

export function GetK8sServices(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetK8sServices'](arg1, arg2, arg3);
}

export function GetK8sStatuses(arg1, arg2) {
  return window['go']['main']['App']['GetK8sStatuses'](arg1, arg2);
}

export function GetLocalEvents(arg1, arg2) {
  return window['go']['main']['App']['GetLocalEvents'](arg1, arg2);
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function GetTopProcesses(arg1, arg2) {
  return window['go']['main']['App']['GetTopProcesses'](arg1, arg2);
}

export function GetWeather(arg1, arg2) {
  return window['go']['main']['App']['GetWeather'](arg1, arg2);
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function RestartK8sDeployment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RestartK8sDeployment'](arg1, arg2, arg3, arg4);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScaleK8sDeployment(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ScaleK8sDeployment'](arg1, arg2, arg3, arg4, arg5);
}

export function UncordonK8sNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['UncordonK8sNode'](arg1, arg2, arg3);
}

export function UpdateLocalEvent(arg1) {
  return window['go']['main']['App']['UpdateLocalEvent'](arg1);
}
